file_format: yaml

opentelemetry-collector:
  enabled: true
  mode: deployment
  replicaCount: 1

jaeger:
  enabled: true

prometheus:
  enabled: true

grafana:
  enabled: true

opensearch:
  enabled: false
