opentelemetry-collector:
  enabled: true
  mode: deployment
  replicaCount: 1

jaeger:
  enabled: true

prometheus:
  enabled: true

grafana:
  enabled: true

opensearch:
  enabled: false

components:
  recommendation:
    imageOverride:
      repository: 650032249451.dkr.ecr.us-east-1.amazonaws.com/recommendation
      tag: dev
